# Generated by Django 5.2.8 on 2025-12-13 15:00

import chapters.mixins
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['order'],
            },
            bases=(chapters.mixins.OrderingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('content', tinymce.models.HTMLField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10, verbose_name='Difficulty Level')),
                ('slug', models.SlugField(default='in-python', max_length=100, unique=True, verbose_name='Slug')),
                ('estimated_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete this topic in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Estimated Reading Time (minutes)')),
                ('is_free', models.BooleanField(default=True, help_text='Is this topic available for free?', verbose_name='Free Access')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='chapters.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('order',),
            },
            bases=(chapters.mixins.OrderingMixin, models.Model),
        ),
    ]
