# Generated by Django 5.2.8 on 2025-11-30 20:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
