# Generated by Django 5.2.8 on 2025-12-03 13:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_alter_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('order',), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('advanced', 'Advanced')], default='easy', max_length=10, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Estimated time to complete this topic in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Estimated Reading Time (minutes)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='has_exercises',
            field=models.BooleanField(default=True, help_text='Does this topic include practical exercises?', verbose_name='Has Exercises'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Is this topic available for free?', verbose_name='Free Access'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='chapters.chapter', verbose_name='Chapter'),
        ),
    ]
