# Generated by Django 5.2.8 on 2025-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_alter_topic_options_topic_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=10, verbose_name='Difficulty Level'),
        ),
    ]
