# Generated by Django 5.2.8 on 2025-12-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_topic_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='has_exercises',
        ),
    ]
