# Generated by Django 5.2.8 on 2025-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('manual', models.FileField(upload_to='media/manuals/', verbose_name='Book')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='beginner', max_length=20, verbose_name='Level')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('tag', models.ManyToManyField(blank=True, related_name='manuals', to='manuals.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuals',
            },
        ),
    ]
