# Generated by Django 5.2.8 on 2025-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='manual',
            name='slug',
            field=models.SlugField(default='python-manual', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
