# Generated by Django 5.2.8 on 2025-12-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_alter_tag_options_manual_slug_tag_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
